# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/app.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/app.proto", :syntax => :proto3) do
    add_message "app.InpNum" do
      optional :a, :int32, 1
      optional :b, :int32, 2
    end
    add_message "app.Total" do
      optional :result, :int32, 1
    end
  end
end

module App
  InpNum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("app.InpNum").msgclass
  Total = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("app.Total").msgclass
end
