# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/app.proto for package 'app'

require 'grpc'
require_relative 'app_pb'

module App
  module App
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'app.App'

      rpc :sum, InpNum, Total
    end

    Stub = Service.rpc_stub_class
  end
end
