repos:
- repo: local
  hooks:
  - id: rubocop
    entry: docker-compose run rubocop bundle exec rubocop
    name: rubocop
    language: ruby
    types: []
    args: ['--color', '--only-recognized-file-types']
    exclude: 'mecab_service_pb'

    