version: "3.8"
services:
  mecab:
    build: ./server
    volumes:
      - ./server:/mecab
      - ./mecab_services_pb:/mecab_services_pb
    ports:
      - "8000:8000"
  client:
    build: ./client
    volumes:
      - ./client:/client
      - ./mecab_services_pb:/mecab_services_pb
  rubocop:
    build: ./rubocop
    volumes:
      - ./:/app