version: "3.8"
services:
  mecab:
    build: .
    volumes:
      - ./:/mecab
    ports:
      - "8000:8000"
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/client
      - ./mecab_services_pb:/client/mecab_services_pb